[package]
name = "shopping-list-server"
version = "0.1.0"
authors = ["'Timo Freiberg' <'timo.freiberg@gmail.com'>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6"
rocket = { version = "0.4" }
rocket_contrib = { version = "0.4", default-features = false, features = ["json"] }
serde = "1"
serde_json = "1"
sqlx = "0.3"
thiserror = "1"
time = { version = "0.2", features = ["serde"] }
