name: cd

on:
  workflow_run:
    workflows: ci
    types: ["completed"]

concurrency:
  group: cd
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag shopping-list:latest
    - uses: superfly/flyctl-actions@master
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      with:
        args: "deploy"
