name: ci-cd

on:
  push:
    branches: [ main ]

concurrency:
  group: ci-cd
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test-rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: [target, $HOME/.cargo]
        # An explicit key for restoring and saving the cache
        key: rust-cache
    - name: Run tests
      run: cargo test --verbose

  test-npm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./shopping-list-frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
       #   cache: 'npm'
      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: node_modules
          # An explicit key for restoring and saving the cache
          key: npm-cache
      - run: npm ci
      - run: npm test

  docker:
    runs-on: ubuntu-latest
    needs: [test-rust, test-npm]
    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag shopping-list:latest
    - uses: superfly/flyctl-actions@master
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      with:
        args: "deploy"
