name: ci-cd

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    - '.gitignore'
    - 'start-db.sh'

concurrency:
  group: ci-cd
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test-rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        path: |
          target
          $HOME/.cargo
        key: rust-cache
    - name: Run tests
      run: cargo test --verbose

  test-npm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./shopping-list-frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
       #   cache: 'npm'
      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: node_modules
          # An explicit key for restoring and saving the cache
          key: npm-cache
      - run: npm ci
      - run: npm test

  docker:
    runs-on: ubuntu-latest
    needs: [test-rust, test-npm]
    steps:

    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        file: Dockerfile
        push: false
        # load: true generates a docker image, which we need for fly later
        load: true
        tags: shopping-list:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

    - uses: superfly/flyctl-actions@master
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      with:
        args: "deploy"

      # This ugly bit is necessary if you don't want your cache to grow forever
      # till it hits GitHub's limit of 5GB.
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
