name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

  test-rust:
    runs-on: ubuntu-latest
    steps:
#     - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: target
        # An explicit key for restoring and saving the cache
        key: rust-cache

  test-npm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./shopping-list-frontend
    steps:
#       - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
       #   cache: 'npm'
      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: node_modules
          # An explicit key for restoring and saving the cache
          key: npm-cache
      - run: npm ci
      - run: npm test
